import sys
import os

from pymysql import STRING
myDir = os.getcwd()
sys.path.append(myDir)


from PyQt5 import QtCore, QtGui, QtWidgets
from Controllers.ventaController import ventaController
from Models.Product import Product
from Database.Connection import connection


class Ui_venta(object):

    def __init__(self):
        self.ventaController = ventaController(self)
        self.product = Product(connection())

    def setupUi(self, venta):
        venta.setObjectName("venta")
        venta.resize(1020, 668)
        venta.setStyleSheet("\n"
"\n"
"\n"
"QTableWidget{\n"
"background-color:rgb(187, 235, 255);\n"
"}")
        self.codcliente = QtWidgets.QLabel(venta)
        self.codcliente.setGeometry(QtCore.QRect(60, 50, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.codcliente.setFont(font)
        self.codcliente.setObjectName("codcliente")
        self.input_descuento = QtWidgets.QLineEdit(venta)
        self.input_descuento.setGeometry(QtCore.QRect(850, 290, 113, 16))
        self.input_descuento.setObjectName("input_descuento")
        self.descuento = QtWidgets.QLabel(venta)
        self.descuento.setGeometry(QtCore.QRect(850, 270, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.descuento.setFont(font)
        self.descuento.setObjectName("descuento")
        self.fecha = QtWidgets.QLabel(venta)
        self.fecha.setGeometry(QtCore.QRect(820, 10, 41, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.fecha.setFont(font)
        self.fecha.setObjectName("fecha")
        self.condpago = QtWidgets.QLabel(venta)
        self.condpago.setGeometry(QtCore.QRect(310, 100, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.condpago.setFont(font)
        self.condpago.setObjectName("condpago")
        self.table_venta = QtWidgets.QTableWidget(venta)
        self.table_venta.setGeometry(QtCore.QRect(70, 230, 751, 331))
        self.table_venta.setObjectName("table_venta")
        self.table_venta.setColumnCount(7)
        self.table_venta.setRowCount(20)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setKerning(True)
        item.setFont(font)
        self.table_venta.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.table_venta.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setItem(0, 2, item)
        self.input_hora = QtWidgets.QTimeEdit(venta)
        self.input_hora.setGeometry(QtCore.QRect(860, 30, 111, 16))
        self.input_hora.setObjectName("input_hora")
        self.neto = QtWidgets.QLabel(venta)
        self.neto.setGeometry(QtCore.QRect(850, 220, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.neto.setFont(font)
        self.neto.setObjectName("neto")
        self.input_direccion = QtWidgets.QLineEdit(venta)
        self.input_direccion.setGeometry(QtCore.QRect(350, 70, 161, 16))
        self.input_direccion.setObjectName("input_direccion")
        self.Botonbuscar = QtWidgets.QPushButton(venta)
        self.Botonbuscar.setGeometry(QtCore.QRect(420, 160, 75, 23))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Imagenes/buscar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Botonbuscar.setIcon(icon)
        self.Botonbuscar.setIconSize(QtCore.QSize(15, 20))
        self.Botonbuscar.setObjectName("Botonbuscar")
        self.Boton_finalizar = QtWidgets.QPushButton(venta)
        self.Boton_finalizar.setGeometry(QtCore.QRect(850, 460, 141, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 200, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 212, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 113, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 128, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 128, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 212, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 200, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 212, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 113, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 128, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 128, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 212, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 234, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 200, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 212, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 113, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 234, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 234, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 128, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 128, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.Boton_finalizar.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Boton_finalizar.setFont(font)
        self.Boton_finalizar.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Imagenes/png-transparent-green-grass-symbol-logo-dialog-box-accept-yellow-circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Boton_finalizar.setIcon(icon1)
        self.Boton_finalizar.setObjectName("Boton_finalizar")
        self.input_neto = QtWidgets.QLineEdit(venta)
        self.input_neto.setGeometry(QtCore.QRect(850, 240, 113, 16))
        self.input_neto.setObjectName("input_neto")
        self.Boton_cancelar = QtWidgets.QPushButton(venta)
        self.Boton_cancelar.setGeometry(QtCore.QRect(850, 540, 141, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(248, 234, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 234, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 128, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 128, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 234, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 234, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 128, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 128, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 234, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 234, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 234, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 128, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 128, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Boton_cancelar.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Boton_cancelar.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Imagenes/png-transparent-computer-icons-cancel-button-miscellaneous-trademark-internet.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Boton_cancelar.setIcon(icon2)
        self.Boton_cancelar.setIconSize(QtCore.QSize(30, 15))
        self.Boton_cancelar.setObjectName("Boton_cancelar")
        self.input_codcliente = QtWidgets.QLineEdit(venta)
        self.input_codcliente.setGeometry(QtCore.QRect(60, 70, 71, 16))
        self.input_codcliente.setObjectName("input_codcliente")
        self.codprod = QtWidgets.QLabel(venta)
        self.codprod.setGeometry(QtCore.QRect(70, 160, 125, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.codprod.setFont(font)
        self.codprod.setObjectName("codprod")
        self.input_ordencompra = QtWidgets.QLineEdit(venta)
        self.input_ordencompra.setGeometry(QtCore.QRect(650, 100, 71, 16))
        self.input_ordencompra.setObjectName("input_ordencompra")
        self.NroOrden = QtWidgets.QLabel(venta)
        self.NroOrden.setGeometry(QtCore.QRect(540, 100, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.NroOrden.setFont(font)
        self.NroOrden.setObjectName("NroOrden")
        self.input_condIVA = QtWidgets.QLineEdit(venta)
        self.input_condIVA.setGeometry(QtCore.QRect(120, 100, 141, 16))
        self.input_condIVA.setObjectName("input_condIVA")
        self.input_codprod = QtWidgets.QLineEdit(venta)
        self.input_codprod.setGeometry(QtCore.QRect(200, 160, 133, 20))
        self.input_codprod.setObjectName("input_codprod")
        self.direccion = QtWidgets.QLabel(venta)
        self.direccion.setGeometry(QtCore.QRect(350, 50, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.direccion.setFont(font)
        self.direccion.setObjectName("direccion")
        self.localidad = QtWidgets.QLabel(venta)
        self.localidad.setGeometry(QtCore.QRect(550, 50, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.localidad.setFont(font)
        self.localidad.setObjectName("localidad")
        self.input_nombre = QtWidgets.QLineEdit(venta)
        self.input_nombre.setGeometry(QtCore.QRect(160, 70, 161, 16))
        self.input_nombre.setObjectName("input_nombre")
        self.input_fecha = QtWidgets.QDateEdit(venta)
        self.input_fecha.setGeometry(QtCore.QRect(860, 10, 110, 16))
        self.input_fecha.setObjectName("input_fecha")
        self.input_condpago = QtWidgets.QLineEdit(venta)
        self.input_condpago.setGeometry(QtCore.QRect(380, 100, 141, 16))
        self.input_condpago.setObjectName("input_condpago")
        self.nombre = QtWidgets.QLabel(venta)
        self.nombre.setGeometry(QtCore.QRect(160, 50, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.nombre.setFont(font)
        self.nombre.setObjectName("nombre")
        self.condIVA = QtWidgets.QLabel(venta)
        self.condIVA.setGeometry(QtCore.QRect(60, 100, 51, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.condIVA.setFont(font)
        self.condIVA.setObjectName("condIVA")
        self.label = QtWidgets.QLabel(venta)
        self.label.setGeometry(QtCore.QRect(60, 20, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.input_localidad = QtWidgets.QLineEdit(venta)
        self.input_localidad.setGeometry(QtCore.QRect(550, 70, 171, 16))
        self.input_localidad.setObjectName("input_localidad")
        self.hora = QtWidgets.QLabel(venta)
        self.hora.setGeometry(QtCore.QRect(820, 30, 41, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.hora.setFont(font)
        self.hora.setObjectName("hora")
        self.boton_aceptar = QtWidgets.QPushButton(venta)
        self.boton_aceptar.setGeometry(QtCore.QRect(340, 160, 75, 23))
        self.boton_aceptar.setObjectName("boton_aceptar")
        self.efectivo = QtWidgets.QLabel(venta)
        self.efectivo.setGeometry(QtCore.QRect(120, 570, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.efectivo.setFont(font)
        self.efectivo.setObjectName("efectivo")
        self.input_efectivo = QtWidgets.QLineEdit(venta)
        self.input_efectivo.setGeometry(QtCore.QRect(190, 570, 133, 20))
        self.input_efectivo.setObjectName("input_efectivo")
        self.cambio = QtWidgets.QLabel(venta)
        self.cambio.setGeometry(QtCore.QRect(350, 570, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.cambio.setFont(font)
        self.cambio.setObjectName("cambio")
        self.input_cambio = QtWidgets.QLineEdit(venta)
        self.input_cambio.setGeometry(QtCore.QRect(410, 570, 133, 20))
        self.input_cambio.setObjectName("input_cambio")
        self.total = QtWidgets.QLabel(venta)
        self.total.setGeometry(QtCore.QRect(570, 570, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.total.setFont(font)
        self.total.setObjectName("total")
        self.input_total = QtWidgets.QLineEdit(venta)
        self.input_total.setGeometry(QtCore.QRect(620, 570, 133, 20))
        self.input_total.setObjectName("input_total")
        self.boton_efectivo = QtWidgets.QPushButton(venta)
        self.boton_efectivo.setGeometry(QtCore.QRect(120, 600, 111, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.boton_efectivo.setFont(font)
        self.boton_efectivo.setObjectName("boton_efectivo")
        self.Boton_ticket = QtWidgets.QPushButton(venta)
        self.Boton_ticket.setGeometry(QtCore.QRect(850, 390, 141, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Boton_ticket.setFont(font)
        self.Boton_ticket.setObjectName("Boton_ticket")
        self.Boton_limpiar = QtWidgets.QPushButton(venta)
        self.Boton_limpiar.setGeometry(QtCore.QRect(850, 500, 141, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.Boton_limpiar.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Boton_limpiar.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Imagenes/limpiar.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Boton_limpiar.setIcon(icon3)
        self.Boton_limpiar.setIconSize(QtCore.QSize(20, 16))
        self.Boton_limpiar.setObjectName("Boton_limpiar")
        self.importe = QtWidgets.QLabel(venta)
        self.importe.setGeometry(QtCore.QRect(850, 320, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.importe.setFont(font)
        self.importe.setObjectName("importe")
        self.input_importe = QtWidgets.QLineEdit(venta)
        self.input_importe.setGeometry(QtCore.QRect(850, 340, 113, 16))
        self.input_importe.setObjectName("input_importe")
        self.label_3 = QtWidgets.QLabel(venta)
        self.label_3.setGeometry(QtCore.QRect(-20, -10, 1051, 721))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("Imagenes/tventa.jpg"))
        self.label_3.setObjectName("label_3")
        self.label_3.raise_()
        self.codcliente.raise_()
        self.input_descuento.raise_()
        self.descuento.raise_()
        self.fecha.raise_()
        self.condpago.raise_()
        self.table_venta.raise_()
        self.input_hora.raise_()
        self.neto.raise_()
        self.input_direccion.raise_()
        self.Botonbuscar.raise_()
        self.Boton_finalizar.raise_()
        self.input_neto.raise_()
        self.Boton_cancelar.raise_()
        self.input_codcliente.raise_()
        self.codprod.raise_()
        self.input_ordencompra.raise_()
        self.NroOrden.raise_()
        self.input_condIVA.raise_()
        self.input_codprod.raise_()
        self.direccion.raise_()
        self.localidad.raise_()
        self.input_nombre.raise_()
        self.input_fecha.raise_()
        self.input_condpago.raise_()
        self.nombre.raise_()
        self.condIVA.raise_()
        self.label.raise_()
        self.input_localidad.raise_()
        self.hora.raise_()
        self.boton_aceptar.raise_()
        self.efectivo.raise_()
        self.input_efectivo.raise_()
        self.cambio.raise_()
        self.input_cambio.raise_()
        self.total.raise_()
        self.input_total.raise_()
        self.boton_efectivo.raise_()
        self.Boton_ticket.raise_()
        self.Boton_limpiar.raise_()
        self.importe.raise_()
        self.input_importe.raise_()

        self.retranslateUi(venta)
        QtCore.QMetaObject.connectSlotsByName(venta)

        self.c = self.boton_aceptar.clicked.connect(lambda:self.ventaController.aceptar(venta,self.input_codprod.text()))

        self.c = self.boton_efectivo.clicked.connect(lambda:self.ventaController.efectivo(venta,self.input_efectivo.text()))
       

    def retranslateUi(self, venta):
        _translate = QtCore.QCoreApplication.translate
        venta.setWindowTitle(_translate("venta", "Form"))
        self.codcliente.setText(_translate("venta", "Cod Cliente"))
        self.descuento.setText(_translate("venta", "Descuento"))
        self.fecha.setText(_translate("venta", "FECHA"))
        self.condpago.setText(_translate("venta", "Cond Pago"))
        item = self.table_venta.verticalHeaderItem(0)
        item.setText(_translate("venta", "1"))
        item = self.table_venta.verticalHeaderItem(1)
        item.setText(_translate("venta", "2"))
        item = self.table_venta.verticalHeaderItem(2)
        item.setText(_translate("venta", "3"))
        item = self.table_venta.verticalHeaderItem(3)
        item.setText(_translate("venta", "4"))
        item = self.table_venta.verticalHeaderItem(4)
        item.setText(_translate("venta", "5"))
        item = self.table_venta.verticalHeaderItem(5)
        item.setText(_translate("venta", "6"))
        item = self.table_venta.verticalHeaderItem(6)
        item.setText(_translate("venta", "7"))
        item = self.table_venta.verticalHeaderItem(7)
        item.setText(_translate("venta", "8"))
        item = self.table_venta.verticalHeaderItem(8)
        item.setText(_translate("venta", "9"))
        item = self.table_venta.verticalHeaderItem(9)
        item.setText(_translate("venta", "10"))
        item = self.table_venta.verticalHeaderItem(10)
        item.setText(_translate("venta", "11"))
        item = self.table_venta.verticalHeaderItem(11)
        item.setText(_translate("venta", "12"))
        item = self.table_venta.verticalHeaderItem(12)
        item.setText(_translate("venta", "13"))
        item = self.table_venta.verticalHeaderItem(13)
        item.setText(_translate("venta", "14"))
        item = self.table_venta.verticalHeaderItem(14)
        item.setText(_translate("venta", "15"))
        item = self.table_venta.verticalHeaderItem(15)
        item.setText(_translate("venta", "16"))
        item = self.table_venta.verticalHeaderItem(16)
        item.setText(_translate("venta", "17"))
        item = self.table_venta.verticalHeaderItem(17)
        item.setText(_translate("venta", "18"))
        item = self.table_venta.verticalHeaderItem(18)
        item.setText(_translate("venta", "19"))
        item = self.table_venta.verticalHeaderItem(19)
        item.setText(_translate("venta", "20"))
        item = self.table_venta.horizontalHeaderItem(0)
        item.setText(_translate("venta", "CODIGO"))
        item = self.table_venta.horizontalHeaderItem(1)
        item.setText(_translate("venta", "CANT."))
        item = self.table_venta.horizontalHeaderItem(2)
        item.setText(_translate("venta", "DESCRIPCION"))
        item = self.table_venta.horizontalHeaderItem(3)
        item.setText(_translate("venta", "PRECIO UNIT"))
        item = self.table_venta.horizontalHeaderItem(4)
        item.setText(_translate("venta", "DTO%"))
        item = self.table_venta.horizontalHeaderItem(5)
        item.setText(_translate("venta", "TOTAL"))
        item = self.table_venta.horizontalHeaderItem(6)
        item.setText(_translate("venta", "STOCK"))
        __sortingEnabled = self.table_venta.isSortingEnabled()
        self.table_venta.setSortingEnabled(False)
        self.table_venta.setSortingEnabled(__sortingEnabled)
        self.neto.setText(_translate("venta", "Neto"))
        self.Botonbuscar.setText(_translate("venta", "Buscar"))
        self.Boton_finalizar.setText(_translate("venta", "Finalizar Venta"))
        self.Boton_cancelar.setText(_translate("venta", "Cancelar Venta"))
        self.codprod.setText(_translate("venta", "CODIGO DE PRODUCTO"))
        self.NroOrden.setText(_translate("venta", "Nro Orden Compra"))
        self.direccion.setText(_translate("venta", "Direccion"))
        self.localidad.setText(_translate("venta", "Localidad"))
        self.nombre.setText(_translate("venta", "Nombre"))
        self.condIVA.setText(_translate("venta", "Cond IVA"))
        self.label.setText(_translate("venta", "FACTURA C"))
        self.hora.setText(_translate("venta", "HORA"))
        self.boton_aceptar.setText(_translate("venta", "Aceptar"))
        self.efectivo.setText(_translate("venta", "Efectivo"))
        self.cambio.setText(_translate("venta", "Cambio"))
        self.total.setText(_translate("venta", "Total"))
        self.boton_efectivo.setText(_translate("venta", "Efectivo Recibido"))
        self.Boton_ticket.setText(_translate("venta", "Ticket"))
        self.Boton_limpiar.setText(_translate("venta", "Limpiar Venta"))
        self.importe.setText(_translate("venta", "Importe"))

        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    venta = QtWidgets.QWidget()
    ui = Ui_venta()
    ui.setupUi(venta)
    venta.show()
    sys.exit(app.exec_())
